
project_id = "crnpusxrbjozxdeeaotw"
[functions.email-service]
verify_jwt = false
[functions.reset-password]
verify_jwt = false
[functions.send-contact-email]
verify_jwt = false
[functions.send-voter-otp]
verify_jwt = false
