// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crnpusxrbjozxdeeaotw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNybnB1c3hyYmpvenhkZWVhb3R3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NTg1MzEsImV4cCI6MjA2MjUzNDUzMX0._xYpsEJE2HkmnTKFaLWdDuOwRavnSdi2L4lQv9M4-ZA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);